export const SET_US_MAP_LOADING_STATUS = 'us-map/SET_LOADING_STATUS'
export const SET_US_MAP_ERROR = 'us-map/SET_ERROR'
export const FETCH_US_MAP_DATA = 'us-map/FETCH_DATA'
export const SET_US_MAP_DATA = 'us-map/SET_DATA'
export const SET_US_MAP_ATTRIBUTES = 'us-map/SET_ATTRIBUTES'
export const APPLY_US_MAP_PROJECTION = 'us-map/APPLY_PROJECTION'
export const LOAD_US_COUNTIES = 'us-map/LOAD_COUNTIES'
export const LOAD_US_STATES = 'us-map/LOAD_STATES'

export const FETCH_US_COMMUTE_DATA = 'us-commute/FETCH_DATA'
export const SET_US_COMMUTE_DATA = 'us-commute/SET_DATA'
export const APPLY_COLOR_SCALE_TO_FILTERED_COMMUTE_DATA = 'us-commute/APPLY_COLOR_SCALE'
